# Generated by Django 3.2.6 on 2021-08-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20210819_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_embed_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
